In [21]:
import pandas as pd
import cv2
import os
import random
import matplotlib.pyplot as plt
import pickle
import numpy as np

In [22]:
directory="D:\Projects\cat vs dog\dogscats"
categories=['cats','dogs']

In [32]:
data=[]
for category in categories:
    folder=os.path.join(directory,category)
    label=categories.index(category)
    for img in os.listdir(folder):
        img_path=os.path.join(folder,img)
        img_arr=cv2.imread(img_path)
        img_arr=cv2.resize(img_arr,(144,144))
        data.append([img_arr,label])

[[[ 12  57  60]
  [ 14  57  60]
  [ 18  55  63]
  ...
  [ 13  14  12]
  [ 12  10   9]
  [ 47  45  44]]

 [[  8  53  56]
  [ 10  53  56]
  [ 14  51  59]
  ...
  [ 35  37  37]
  [ 17  19  19]
  [ 15  17  17]]

 [[  4  49  52]
  [  6  49  52]
  [ 11  47  55]
  ...
  [ 19  25  30]
  [ 13  19  24]
  [ 15  21  26]]

 ...

 [[102 164  44]
  [103 165  45]
  [104 166  46]
  ...
  [103 158  31]
  [101 156  29]
  [103 158  31]]

 [[102 164  44]
  [103 165  45]
  [103 165  45]
  ...
  [101 158  29]
  [ 99 157  25]
  [100 158  26]]

 [[102 164  44]
  [103 165  45]
  [103 165  45]
  ...
  [100 157  28]
  [ 97 155  23]
  [ 98 156  24]]]
[[[ 11  10  12]
  [ 25  24  26]
  [ 21  16  17]
  ...
  [ 33  37  32]
  [ 71  75  70]
  [ 37  40  38]]

 [[ 13  12  14]
  [ 20  19  21]
  [ 27  22  23]
  ...
  [ 27  30  28]
  [ 65  68  66]
  [ 30  32  32]]

 [[ 11  10  12]
  [  6   5   7]
  [ 27  22  23]
  ...
  [ 21  23  23]
  [ 57  59  59]
  [ 19  21  22]]

 ...

 [[  6   9   7]
  [  6   9   7]
  [  7  10   8]
  ..

In [24]:
len(data)

2000

In [25]:
random.shuffle(data)

In [26]:
x=[]
y=[]
for features,lables in data:
    x.append(features)
    y.append(lables)

In [27]:
x=np.array(x)
y=np.array(y)

In [35]:
x=x/255

In [37]:
x.shape

(2000, 144, 144, 3)

In [38]:
import tensorflow

In [39]:
from keras.models import Sequential
from keras.layers import Conv2D,MaxPool2D,Flatten,Dense

In [44]:
model=Sequential()
model.add(Conv2D(64,(3,3),activation='relu'))
model.add(MaxPool2D(2,2))

model.add(Conv2D(64,(3,3),activation='relu'))
model.add(MaxPool2D(2,2))

model.add(Conv2D(64,(3,3),activation='relu'))
model.add(MaxPool2D(2,2))

model.add(Flatten())

model.add(Dense(128,input_shape=x.shape[1:]))

model.add(Dense(2,activation='softmax'))

In [45]:
model.compile(optimizer='adam',loss='sparse_categorical_crossentropy',metrics=['accuracy'])

In [46]:
model.fit(x,y,epochs=10,validation_split=0.1)

Epoch 1/10
57/57 [==============================] - 19s 327ms/step - loss: 0.7665 - accuracy: 0.5450 - val_loss: 0.6666 - val_accuracy: 0.6400
Epoch 2/10
57/57 [==============================] - 19s 329ms/step - loss: 0.6682 - accuracy: 0.5911 - val_loss: 0.6684 - val_accuracy: 0.6200
Epoch 3/10
57/57 [==============================] - 19s 333ms/step - loss: 0.6187 - accuracy: 0.6628 - val_loss: 0.6488 - val_accuracy: 0.6400
Epoch 4/10
57/57 [==============================] - 19s 335ms/step - loss: 0.5633 - accuracy: 0.7089 - val_loss: 0.6474 - val_accuracy: 0.6400
Epoch 5/10
57/57 [==============================] - 19s 336ms/step - loss: 0.5034 - accuracy: 0.7539 - val_loss: 0.6512 - val_accuracy: 0.6300
Epoch 6/10
57/57 [==============================] - 19s 338ms/step - loss: 0.4565 - accuracy: 0.7844 - val_loss: 0.7163 - val_accuracy: 0.6600
Epoch 7/10
57/57 [==============================] - 19s 335ms/step - loss: 0.3841 - accuracy: 0.8239 - val_loss: 0.7940 - val_accuracy: 0.6000